[build]
  command = "rm -rf node_modules package-lock.json && npm install --no-package-lock && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
